[release]
current-version = "0.0.1-alpha.0"

version-files = [
    "pyproject.toml",
]

commit-message = "Release v{version}"
branch-name = "release/v{version}"
push = true
confirm = true

[changelog.section-labels]
"Bug Fixes" = ["bug"]
"Performance" = ["performance"]
"Configuration" = ["configuration"]
"Documentation" = ["documentation"]
"Dependencies" = ["dependencies"]

[changelog]
ignore-contributors = ["dependabot[bot]"]
ignore-labels = ["internal", "ci", "needs-decision", "wish", "testing"]
include-contributors = true
changelog-heading = "{version}"
